### ISSUE TITLE
Ghana Features to Merge Back to SORMAS Main Branch

### ISSUE THREAD

**Issue by isaacanip** [ePareto-Information-System/SORMAS-Project#138]
### Feature Description

Tasks to be performed on Ghana Features to Merge Back to SORMAS Main Branch

### Added Value/Benefit

SORMAS foundation request Ghana features (i.e. Password reset and disease dashboard) to be merged back to SORMAS Main Branch.

### Acceptance Criteria

- [ ] ePareto: Creates the Epic for both features on SORMAS GitHub Repository from ePareto GitHub account(Until 10th January 2024).
- [ ] ePareto: Create a feature branch/fork (with EPIC #) from the development branch and inform SF(Until 11th January 2024).
- [ ] ePareto: Import or integrate the code into the feature branch/fork (Until 17th January 2024).
- [ ] ePareto: Start QA by checking the code (Until 22nd January 2024).
- [ ] ePareto: Perform final commit into feature branch/fork and inform SF (Until 23rd January 2024)
- [ ] SORMAS Foundation: Take the feature branch/fork, test code locally and when everything is fine ePareto will do a Pull Request to merge with the development branch (Until 29th January 2024).
- [ ] SORMAS Foundation: Approve the request to the development branch (Until 31st January 2024).
- [ ] SORMAS Foundation: Merge the Development branch into the master branch when the new version of SORMAS is released(The date is not defined yet).

## Epic Table
| Title                  |                 Assignee |  State | 
|---|---|---|

- | #6     |  @faatihi   |   Closed  | 

- |  #21 |   @Anthony4m   |   Closed  |
