### ISSUE TITLE
Resolve extra facilities found in SORMAS compared to DHIMS

### ISSUE THREAD

**Issue by isaacanip** [ePareto-Information-System/SORMAS-Project#25]
### Problem Description

Facilities found at both SORMAS and DHIMS must always match. It so happens that facilities in SORMAS are more than the ones in DHIMS.
### Proposed Solution

Use DHIMS as benchmark to resolve extra facilities found in SORMAS.

### Tasks (73/245 facilities)

- [ ] **Ahafo** region (9 facilities)
  - [ ] collect confirmation status from GHS (0/9)
  - [ ] assign action to be taken (0/9)
  - [ ] take action on live server (0/9)
- [ ] **Ashanti** region (49 facilities)
  - [ ] collect confirmation status from GHS (38/49)
  - [ ] assign actions to be taken (38/49)
  - [ ] take action on live server (38/49)
- [ ] **Bono** region (3 facilities)
  - [ ] collect confirmation status from GHS (0/3)
  - [ ] assign action to be taken (0/3)
  - [ ] take action on live server (0/3)
- [ ] **Bono East** region (2 facilities)
  - [ ] collect confirmation status from GHS (0/2)
  - [ ] assign action to be taken (0/2)
  - [ ] take action on live server (0/2)
- [x] **Eastern** region (35 facilities)
  - [x] collect confirmation status from GHS (35/35)
  - [x] assign action to be taken (35/35)
  - [x] take action on live server (35/35)
- [ ] **Greater Accra** region (77 facilities)
  - [ ] collect confirmation status from GHS (0/77)
  - [ ] assign action to be taken (0/77)
  - [ ] take action on live server (0/77)
- [ ] **North East** region (1 facility)
  - [ ] collect confirmation status from GHS (0/1)
  - [ ] assign action to be taken (0/1)
  - [ ] take action on live server (0/1)
- [ ] **Northern** region (20 facility)
  - [ ] collect confirmation status from GHS (0/20)
  - [ ] assign action to be taken (0/20)
  - [ ] take action on live server (0/20)
- [ ] **Oti** region (7 facilities)
  - [ ] collect confirmation status from GHS (0/7)
  - [ ] assign action to be taken (0/7)
  - [ ] take action on live server (0/7)
- [ ] **Savannah** region (11 facilities)
  - [ ] collect confirmation status from GHS (0/11)
  - [ ] assign action to be taken (0/11)
  - [ ] take action on live server (0/11)
- [ ] **Upper East** region (4 facilities)
  - [ ] collect confirmation status from GHS (0/4)
  - [ ] assign action to be taken (0/4)
  - [ ] take action on live server (0/4)
- [ ] **Upper West** region (2 facilities)
  - [ ] collect confirmation status from GHS (0/2)
  - [ ] assign action to be taken (0/2)
  - [ ] take action on live server (0/2)
- [ ] **Volta** region (3 facilities)
  - [ ] collect confirmation status from GHS (0/3)
  - [ ] assign action to be taken (0/3)
  - [ ] take action on live server (0/3)
- [ ] **Western** region (13 facilities)
  - [ ] collect confirmation status from GHS (0/13)
  - [ ] assign action to be taken (0/13)
  - [ ] take action on live server (0/13)
- [ ] **Western North** region (9 facilities)
  - [ ] collect confirmation status from GHS (0/9)
  - [ ] assign action to be taken (0/9)
  - [ ] take action on live server (0/9)

**Comment by faatihi** [comment]
- [ ] Eastern region
- [ ] Ashanti region
