### ISSUE TITLE
Disease dashboard

### ISSUE THREAD

**Issue by faatihi** [ePareto-Information-System/SORMAS-Project#6]
Original issue here: https://github.com/hzi-braunschweig/SORMAS-Project/issues/1529

**Comment by user-yormen** [comment]
The disease drilldown feature is now ready for review.

![image](https://user-images.githubusercontent.com/24682056/145847191-1f3c5829-b04f-4d1d-864c-35038b74109f.png)

**Comment by faatihi** [comment]
Beautiful. Well done, Reggie. I'll go through

**Comment by user-yormen** [comment]
GITHUB link: 
https://github.com/ePareto-Information-System/SORMAS-Project/tree/dashboard-disease-clickable-details

**Comment by user-yormen** [comment]
The filter should be worked on.

Seems it has been made independent on the class level, so contact dashboard has its own filter component, surveillance dashboard has it own and so on. 

So this feature should be made to have it own as well.

**Comment by user-yormen** [comment]
Click on the ellipses(...) to view the disease details 

![image](https://user-images.githubusercontent.com/24682056/171227857-20db7581-3920-49e2-ab1f-642b3fd30fe8.png)

**Comment by isaacanip** [comment]
**General findings after UAT on Disease drill down - Additional tasks**
- [x] Restructure drill down query to match parent query.
    - [x]  Include inactive cases in drill down query structure.
    - [x]  Display districts at disease drill down when a region is selected on surveillance dashboard.
    - [x]  Set Null values in "Outcome of case" field to "No outcome yet".
    - [x]   Include "Unknown" and "other" on the disease drill down dashboard.
