### ISSUE TITLE
Merge Approved reviews to gh-uat (sormas 1.74.3)

### ISSUE THREAD

**Issue by user-yormen** [ePareto-Information-System/SORMAS-Project#91]

**Comment by user-yormen** [comment]
- [x] Create a new branch gh-uat from gh-release-1.68.0
- [x] Pull and update development branch and merge that into the gh-uat(Conflict Resolution)
- [x] Class compilation and error resolution
- [x] Run Merged branch to confirm everything works fine
- [ ] Merged, resolve conflicts, compilation resolution and push changes to git
Merge reviewed branches to gh-uat 

> - [x]   Merged with test_auto_deploy
  > - [x]  Contact statistics #10 
> - [x]   Allow users to change password #21 
> - [x]  More mandatory fields and validation #48 
> - [x]  Separate latitude and longitude during export #11 
> - [x]  Negative test results not a case #14 
> - [x]  Case/contacts without coordinate #13 
> - [ ]  Cadre/position to person tab #34 
> - [x]  Bulk sample transfer to another lab #39 
> - [ ]  Dashboard display confirm cases only #12 
> - [x]  Add new role hospital supervisor #15 
> - [x]  Dashboard modification #18 
> - [x]  Sample dashboard modification #17 
> - [ ]  Finalize on sample dashboard #7 
> - [x]  New user form gps aligment #16 
> - [x]  Add pathogen test type to filter #5 
> - [x]  Shape file #44 
> - [ ] Disease Drill Down #6 

- [ ] Run the new merged to confirm all the GH features are in it

**Comment by daveotengo** [comment]
Merge reviewed branches to gh-uat 

- [x]   Merged with test_auto_deploy
- [x]  Contact statistics #10 
- [x]  Responsible Region and District are greyed out and causes null pointer exception if ignored #124
- [x]   Allow users to change password #21 
- [x]  More mandatory fields and validation #48 
- [x]  Separate latitude and longitude during export #11 
- [x]  Negative test results not a case #14 
- [x]  Case/contacts without coordinate #13 
- [x]  Cadre/position to person tab #34 
- [x]  Bulk sample transfer to another lab #39 
- [x]  Dashboard display confirm cases only #12 
- [x]  Add new role hospital supervisor #15 
- [x]  Dashboard modification #18 
- [x]  Sample dashboard modification #17 
- [x]  Finalize on sample dashboard #7 
- [x]  New user form gps aligment #16 
- [x]  Add pathogen test type to filter #5 
- [x]  Shape file #44 
- [x] Disease Drill Down #6 

- [ ] Run the new merged to confirm all the GH features are in it

**Comment by isaacanip** [comment]
UAT in Progress for Sormas ver 1.74.3

- [x] @daveotengo Contact statistics https://github.com/ePareto-Information-System/SORMAS-Project/issues/10 | **Error occurred**. [Click to view video.](https://watch.screencastify.com/v/pTBMJ5DM78y1q0AnKyKj)
- [x] Responsible Region and District are greyed out and causes null pointer exception if ignored https://github.com/ePareto-Information-System/SORMAS-Project/issues/124
- [x] Cases and Contact Dashboard Map  [Dashboard map: include cases/contacts that don't have location coordinates](https://github.com/ePareto-Information-System/SORMAS-Project/issues/13#top)
     _[View](https://github.com/ePareto-Information-System/SORMAS-Project/issues/13#issuecomment-1352839899) issue tasks for the dashboard map._
- [x] Allow users to change password https://github.com/ePareto-Information-System/SORMAS-Project/issues/21
- [x] More mandatory fields and validation https://github.com/ePareto-Information-System/SORMAS-Project/issues/48
- [x] Separate latitude and longitude during export https://github.com/ePareto-Information-System/SORMAS-Project/issues/11
- [x] Negative test results not a case https://github.com/ePareto-Information-System/SORMAS-Project/issues/14
- [x] @daveotengo   Case/contacts without coordinate https://github.com/ePareto-Information-System/SORMAS-Project/issues/13 | **GPS coordinate** [shows in v1.71.0](https://watch.screencastify.com/v/RYwYvmUPn8WRyiiuJwqq) and [not in v1.74.3](https://watch.screencastify.com/v/TaXZdB0Ry1VoV1wis6sD
).
- [x] Cadre/position to person tab https://github.com/ePareto-Information-System/SORMAS-Project/issues/34
- [x] Bulk sample transfer to another lab https://github.com/ePareto-Information-System/SORMAS-Project/issues/39
     - [x] _[View](https://github.com/ePareto-Information-System/SORMAS-Project/issues/39#issuecomment-1356267230) bulk sample transfer issue._
- [x] Dashboard display confirm cases only https://github.com/ePareto-Information-System/SORMAS-Project/issues/12
- [x] Add new role hospital supervisor https://github.com/ePareto-Information-System/SORMAS-Project/issues/15 |**Error Occured.[[Click to view UAT video](https://watch.screencastify.com/v/ehqBJemaX7DpxC7yvKIi)]
- [x] Dashboard modification https://github.com/ePareto-Information-System/SORMAS-Project/issues/18
- [x] Sample dashboard modification https://github.com/ePareto-Information-System/SORMAS-Project/issues/17
- [x] Finalize on sample dashboard https://github.com/ePareto-Information-System/SORMAS-Project/issues/7
- [x] New user form gps aligment https://github.com/ePareto-Information-System/SORMAS-Project/issues/16
- [x] Add pathogen test type to filter https://github.com/ePareto-Information-System/SORMAS-Project/issues/5
- [x] Shape file https://github.com/ePareto-Information-System/SORMAS-Project/issues/44
     _Issues found under the shape files are as follows:_
     - [x] _Statistics/Contact/Visualization/Map/Regions: Clicking on the "Generate" button thrown up an error after navigating to the stated path._
     - [x] _Statistics/Contact/Visualization/Map/District: Clicking on the "Generate" button thrown up an error after navigating to the stated path._
- [x] Disease Drill Down https://github.com/ePareto-Information-System/SORMAS-Project/issues/6
           _Disease dashboard has some tasks needed to be accomplished._
     - [x] _Disease count on Surveillance dashboard must reflect Disease count on Disease dashboard. [See video]_(https://watch.screencastify.com/v/MLeIY4CE6FssgNIDyo9m).
     - [x] _The region values on the disease dashboard are wrongly represented._
     - [x] _The total percentage % distribution on the disease dashboard does not add up to 100%._
     - [x] _The disease count for each region must be beside the % distribution. See below picture for example._ 
![image](https://user-images.githubusercontent.com/60930711/208236839-0c5e1e4d-85e6-4afd-856a-746cf727ba76.png)

**Comment by isaacanip** [comment]
26.03.2023: Completed
